import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./Footer";
import Loader from "../components/Loader";
import PageLoader from "../components/PageLoader";
import AIAssistant from "../components/AIAssistant";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
  <Loader />
  <PageLoader />
        <Navbar />
        <div className="min-h-[60vh] flex flex-col">
          <main className="flex-1">{children}</main>
        </div>
        <Footer />
        <AIAssistant />
      </body>
    </html>
  );
}
